version: '3'
services:
  my-back-service:
    image: imagedb
    environment:
      - BACK_ENV_VARIABLE=production
    ports:
      - "5001:5000"
    volumes:
      - backend-data:/path/to/data/directory

  my-front-service:
    image: imagefront
    environment:
      - FRONT_ENV_VARIABLE=production
      - WS_BACK_URL=http://my-back-service:5000
    ports:
      - "8080:80"

volumes:
  backend-data:
