version: '3'
services:
  my-back-service:
    image: imagedb
    environment:
      - MY_ENV_VARIABLE=production
    ports:
      - "5001:5000"
    volumes:
      - /path/to/host/directory:/path/in/container
